require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true
platform :ios, '10.0'

target 'MyTurboUtilsExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'my-turbo-utils', path: '../..', project_name: 'my-turbo-utils'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper' => '0.80.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end
